CREATE TABLE IF NOT EXISTS short (
    id SERIAL PRIMARY KEY,
    long_url VARCHAR(255) NOT NULL,
    key VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    views INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_short_key ON short (key);
