CREATE TABLE IF NOT EXISTS experience (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    tags VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL
);
