//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "portfolio", table_name = "short")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub long_url: String,
    #[sea_orm(unique)]
    pub key: String,
    pub description: String,
    pub views: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
